<footer  class=" fixed-bottom text-center mt-5" style="margin-top:400px">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="index.php"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown text-center">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="index.php">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="apropos.php">A propos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.php">Contact</a>
          </li>
          <li class="nav-item flex-end"> </li>
        </ul>
      </div>
      <div class="text-right text-white col-4"> Copyright &copy; 2021 <a href="admin/index.php"><img
            src="assets/images/logo_fast3.png" alt="" width="30"></a></div>
    </div>
  </nav>
</footer>

</body>

</html>